version: '3.8'

services:
  game-server:
    build:
      context: ./services/game-server
      dockerfile: Dockerfile.server
    ports:
      - "${GAME_SERVER_PORT:-8080}:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:${REDIS_PORT:-6379}
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_SERVICE_PORT:-8081}
      - CHAT_SERVICE_URL=http://chat-service:${CHAT_SERVICE_PORT:-8082}
      - DEBUG=${DEBUG:-false}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000}

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT:-8081}:8081"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:${REDIS_PORT:-6379}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - DEBUG=${DEBUG:-false}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000}

  chat-service:
    build:
      context: ./services/chat-service
      dockerfile: Dockerfile
    ports:
      - "${CHAT_SERVICE_PORT:-8082}:8082"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:${REDIS_PORT:-6379}
      - DEBUG=${DEBUG:-false}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
      - WS_MAX_CONNECTIONS=${WS_MAX_CONNECTIONS:-1000}
      - WS_MESSAGE_SIZE_LIMIT=${WS_MESSAGE_SIZE_LIMIT:-4096}

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data

  client:
    build:
      context: ./roleplay_client
      dockerfile: Dockerfile.client
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    depends_on:
      - game-server
      - auth-service
      - chat-service
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - GAME_SERVER_URL=http://localhost:${GAME_SERVER_PORT:-8080}
      - AUTH_SERVICE_URL=http://localhost:${AUTH_SERVICE_PORT:-8081}
      - CHAT_SERVICE_URL=http://localhost:${CHAT_SERVICE_PORT:-8082}

volumes:
  redis_data: 