version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  client:
    build:
      context: ./roleplay_client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - server 